LOG: ====================================
LOG: Benchmarking HyCC
LOG: ====================================
LOG: TEST: db_merge
LOG: SELECTION_SCHEME: yaohybrid
LOG: MINIMIZATION_TIME: 600
LOG: ARGUMENTS: ['--all-variants']
LOG: ====================================
LOG: RERUN: 0
LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 3.09 seconds 657316 kB Command exited with non-zero status 134 3.09 seconds 657316 kB
LOG: retry: 0
LOG: ====================================
LOG: RERUN: 0
LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 3.06 seconds 657228 kB Command exited with non-zero status 134 3.06 seconds 657228 kB
LOG: retry: 1
LOG: ====================================
LOG: RERUN: 0
LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 3.07 seconds 657236 kB Command exited with non-zero status 134 3.07 seconds 657236 kB
LOG: retry: 2
LOG: ====================================
LOG: RERUN: 0
LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 3.05 seconds 657328 kB Command exited with non-zero status 134 3.05 seconds 657328 kB
LOG: retry: 3
LOG: ====================================
LOG: RERUN: 0
LOG: Error: Process returned with status code 134
LOG: Error message: terminate called after throwing an instance of 'std::out_of_range'   what():  _Map_base::at Command terminated by signal 6 3.06 seconds 657064 kB Command exited with non-zero status 134 3.06 seconds 657064 kB
LOG: retry: 4
LOG: Failed yaohybrid with args: --all-variants, exception:
